all:
	cd test-logic      && make
	cd test-shift      && make
	cd test-move       && make
	cd test-arithmetic && make
	cd test-jump       && make
	cd test-branch     && make
	cd test-load-store && make
	cd test-load-stall && make
	cd test-forwarding && make

clean:
	rm -rf */test.vcd